version: '1'

services:
   # service sql
  database:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD : 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql

  #Les service PHP sont crée avec des Dockerfile
  php1:
    build: ./dockerfiles
    restart: always
    volumes:
      - './src1:/var/www'
    working_dir: /var/www
    depends_on:
      - database

  php2:
      build: ./dockerfiles
      restart: always
      volumes:
        - './src2:/var/www'
      working_dir: /var/www
      depends_on:
        - database


  nginx1:
      image: nginx:latest
      restart: always
      ports:
        - '80:80'
      volumes:
        - './.docker/nginx1:/etc/nginx/conf.d'
        - './src1:/var/www'
  
  nginx2:
      image: nginx:latest
      restart: always
      ports:
        - '81:80'
      volumes:
        - './.docker/nginx2:/etc/nginx/conf.d'
        - './src2:/var/www'

  #Adminer
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
     - 8080:8080
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
  
  mincraft: 
    build: ./mincraft
    volumes:
      - ./mincraft/server-data:/server
    ports:
      - 25565:25565
      - 25575:25575
    container_name: mincraft_server
    restart: unless-stopped
  
  minio:
    image: quay.io/minio/minio:latest
    ports:
      - 8000:8000
      - 9001:9001
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Docker@123
    command: server --console-address ":9001" /data
  
  
volumes:
  database:
  server-data:
  minio_storage: {}